### ISSUE TITLE
Zenity provides some more complex progress parsing on stdin

### ISSUE THREAD

**Issue by luebking** [luebking/qarma#12]
"#foo" seems to do the comment, need to figure the syntax and extend the parser

**Comment by jmiahman** [comment]
Especially in progress :) not quite a drop in replacement yet

**Comment by luebking** [comment]
Update, the label is the only thing I could really make out (and added that)
Keeping this open in case somebody stumbles over a different related feature.

**Comment by luebking** [comment]
That's actually it…
https://help.gnome.org/users/zenity/stable/progress.html.en
