### ISSUE TITLE
qarma works on mac os sierra!

### ISSUE THREAD

**Issue by maz-1** [luebking/qarma#15]
![snip20170202_2](https://cloud.githubusercontent.com/assets/5277060/22541688/d533db00-e962-11e6-9e7c-dee95caebf0b.png)

**Comment by maz-1** [comment]
This is what you have to do:
1.Install Xcode. Build static qt5 ( http://wohlsoft.ru/pgewiki/Building_static_Qt_5 )
2.Modify PATH to include qmake from static qt5 build
3.Open qarma.pro, remove all X11 related things
4.Run "qmake qarma.pro && make" from source tree
5.There should be qarma.app after make. You can copy qarma.app/Contents/MacOS/qarma to /usr/local/bin for better shell script integration

**Comment by luebking** [comment]
I'm kinda stunned there's zenity/qarma usage on OSX at all ;-)
Can you try whether this patch builds a makefile that works out of the box?

```diff
diff --git a/qarma.pro b/qarma.pro
index ebd0327..d6b745b 100644
--- a/qarma.pro
+++ b/qarma.pro
@@ -1,10 +1,11 @@
 HEADERS = Qarma.h
 SOURCES = Qarma.cpp
-QT      += dbus gui widgets x11extras
+QT      += dbus gui widgets
+unix:QT += x11extras
 TARGET  = qarma
 
-LIBS    += -lX11
-DEFINES += WS_X11
+unix:LIBS    += -lX11
+unix:DEFINES += WS_X11
 
 target.path += /usr/bin
 INSTALLS += target

**Comment by maz-1** [comment]
Nope, But this works
`diff --git a/qarma.pro b/qarma.pro
index ebd0327..d6b745b 100644
--- a/qarma.pro
+++ b/qarma.pro
@@ -1,10 +1,11 @@
 HEADERS = Qarma.h
 SOURCES = Qarma.cpp
-QT      += dbus gui widgets x11extras
+QT      += dbus gui widgets
+unix:!macx:QT += x11extras
 TARGET  = qarma
 
-LIBS    += -lX11
-DEFINES += WS_X11
+unix:!macx:LIBS    += -lX11
+unix:!macx:DEFINES += WS_X11
 
 target.path += /usr/bin
 INSTALLS += target`

See here : http://stackoverflow.com/questions/18462420/how-to-specify-mac-platform-in-qmake-qtcreator
