### ISSUE TITLE
--attach doesnt accept the following entry

### ISSUE THREAD

**Issue by chafporte** [luebking/qarma#19]
zenity does accept this (and so does kdialog):

--attach=$(sleep .01;xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)

zenity/kdialog even accept it if the \t is expanded as a tab

**Comment by luebking** [comment]
Wild guess: do they also accept it if you sleep longer (like 0.1)?

**Comment by chafporte** [comment]
the problem is that
zenity and kdialog both accept --attach 0x25
qarma only takes --attach 37

**Comment by chafporte** [comment]
I fail to see how qarma can pretend to be a zenity drop in replacement if this is not addressed.

**Comment by luebking** [comment]
I closed it with https://github.com/luebking/qarma/commit/e146a25bf7d73815a991d024dccee129b5523fec

**Comment by chafporte** [comment]
thanks, I've tested it, it works fine now.
1) you should add a qarma version number under --version
    maybe the corresponding git number
2) minor issue: on fedora lxqt
    qarma --notification --text "the tittle" 
    it shows the notification, but "the tittle" appears twice in the popup.
thanks again
