### ISSUE TITLE
Exit code on escape

### ISSUE THREAD

**Issue by gen2brain** [luebking/qarma#21]
Qarma doesn't return correct error code when dialog is closed with e.g. escape button.

```
milann@thinkpad ~ $ zenity --info --title "Title" --text "Text"
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
milann@thinkpad ~ $ echo $?
1
milann@thinkpad ~ $ qarma --info --title "Title" --text "Text"
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-milann'
milann@thinkpad ~ $ echo $?
0
```

**Comment by luebking** [comment]
I looked into this and atm. it looks a bit like a bug in Qt - the escape key does not seem to emit rejected() or reject the dialog in any other way.
I'll push a workaround but if you care, you might want to file a bug against Qt - though my impression is that QWidget has effectively been dropped.
