### ISSUE TITLE
Retain the View mode in --file-selection

### ISSUE THREAD

**Issue by AcarBurak** [luebking/qarma#23]
As I find the Detailed View unnecessarily wasteful of my screen real estate I always re-change to the List view in every `--file-selection` launch. It would be very fine if Qarma could retain the View mode, if it's not such a trouble or bloat in your opinion.

Thanks for this very fine and useful application.

**Comment by luebking** [comment]
On what platform? (In doubt: screenshot ;-)
The stock Qt dialog starts on the list view anyway and if this is a platform plugin like from KDE, things could  end up more tricky.

**Comment by AcarBurak** [comment]
Very sorry, I'm on Arch (Fluxbox). Actually I build Qarma from source and before doing this, make the List View the default one! I've just opened this thinking it might be a fine feature especially for those who are provided with a binary one from their repos.

**Comment by AcarBurak** [comment]
> The stock Qt dialog starts on the list view anyway

Well, not Qarma. That's why I compile it after changing the code (default) to List View.

**Comment by luebking** [comment]
Sorry, the Qt API actually announces Detail as default view mode, but it doesn't open here this way.
It's QFileDialog::ViewMode(List) right after the constructor and stays this way.
=> Qt version on your side? (We could make this explicit nevertheless, because the API at least promotes different behavior)

**Comment by AcarBurak** [comment]
I'm not a coder, obviously! But I could manage to change that minor thing before compilation. I would ask to make List View the default, but there might be other use cases requiring the Detail one and thought retaining the mode would be best. So if you make it default fine too (at least for me), but again, I'm fine with compiling it as it is as well.

By the way, Thumbnail View is still not implemented by Qt (5.10), I guess?

**Comment by luebking** [comment]
The patch is trivial, I'm presently mainly interested in why Qt doesn't behave (here) the way it says it does.
Since you're on arch: pacman -Qi qt5-base ?

```diff
diff --git a/Qarma.cpp b/Qarma.cpp
index 4912879..bb228f2 100644
--- a/Qarma.cpp
+++ b/Qarma.cpp
@@ -339,7 +339,9 @@ void Qarma::dialogFinished(int status)
         QVariantList l;
         for (int i = 0; i < dlg->sidebarUrls().count(); ++i)
             l << dlg->sidebarUrls().at(i);
-        QSettings("qarma").setValue("Bookmarks", l);
+        QSettings settings("qarma");
+        settings.setValue("Bookmarks", l);
+        settings.setValue("FileDetails", dlg->viewMode() == QFileDialog::Detail);
     }
 
     if (!(status == QDialog::Accepted || status == QMessageBox::Ok)) {
@@ -638,10 +640,12 @@ char Qarma::showMessage(const QStringList &args, char type)
 char Qarma::showFileSelection(const QStringList &args)
 {
     QFileDialog *dlg = new QFileDialog;
+    QSettings settings("qarma");
+    dlg->setViewMode(settings.value("FileDetails", false).toBool() ? QFileDialog::Detail : QFileDialog::List);
     dlg->setFileMode(QFileDialog::ExistingFile);
     dlg->setOption(QFileDialog::DontConfirmOverwrite, false);
     dlg->setProperty("qarma_separator", "|");
-    QVariantList l = QSettings("qarma").value("Bookmarks").toList();
+    QVariantList l = settings.value("Bookmarks").toList();
     QList<QUrl> bookmarks;
     for (int i = 0; i < l.count(); ++i)
         bookmarks << l.at(i).toUrl();
```

**Comment by AcarBurak** [comment]
Name            : qt5-base
Version         : 5.10.0-3
Description     : A cross-platform application and UI framework
Architecture    : x86_64
URL             : http://qt-project.org/
Licenses        : GPL3  LGPL3  FDL  custom
Groups          : qt  qt5
Provides        : None
Depends On      : libjpeg-turbo  xcb-util-keysyms  xcb-util-renderutil  libgl
                  fontconfig  xdg-utils  xcb-util-wm  libxrender  libxi  sqlite
                  xcb-util-image  icu  pcre2  tslib  libinput  libsm
                  libxkbcommon-x11  libproxy  libcups  double-conversion
Optional Deps   : qt5-svg: to use SVG icon themes [installed]
                  postgresql-libs: PostgreSQL driver
                  libmariadbclient: MariaDB driver
                  unixodbc: ODBC driver
                  libfbclient: Firebird/iBase driver [installed]
                  freetds: MS SQL driver
                  gtk3: GTK platform plugin [installed]
Required By     : libdbusmenu-qt5  libqtxdg  libsysstat  makemkv
                  mkvtoolnix-gui  phonon-qt5  phototonic-git  polkit-qt5
                  poppler-qt5  qbs  qgmailnotifier-git  qlipper-git  qps
                  qt5-multimedia  qt5-script  qt5-sensors  qt5-svg  qt5-tools
                  qt5-x11extras  qt5-xmlpatterns  qtermwidget
Optional For    : cmake  openal  pinentry  v4l-utils
Conflicts With  : qtchooser
Replaces        : None
Installed Size  : 57,77 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Sun 14 Jan 2018 22:51:10 +03
Install Date    : Tue 16 Jan 2018 07:05:30 +03
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

**Comment by AcarBurak** [comment]
In my ignorance, I had figured out to achieve my goal (List View as default) by just inserting this after line 641:

`dlg->setViewMode(QFileDialog::List);`

Seeing your patch above I seem to have been, well, ignorant, though I haven't noticed any adverse side effect. Should I revert back?

**Comment by luebking** [comment]
Yeah, I'm going to push that patch.
QFileDialog does still not default to ::Detail here - and I'm on the exact same package as you (now)

On a wild guess: do you use the KDE Breeze style?

**Comment by AcarBurak** [comment]
Thank you.

No, I use Oxygen, but not its folders; folders adapted/colourised from Rosa icons.

**Comment by luebking** [comment]
Not the icon theme, the GUI style. In doubt post a screenshot ;-)

**Comment by AcarBurak** [comment]
Oh sorry, I use Fusion customised by qt5ct.

**Comment by luebking** [comment]
Nope, not even with the qt5ct platform theme.
Heisenbug.
