### ISSUE TITLE
--text-info --autosave option?

### ISSUE THREAD

**Issue by AcarBurak** [luebking/qarma#24]
Is it easy and desirable to add an `--auto-save` option to editable `--text-info` dialogues? Or is it out of scope of Qarma?

**Comment by luebking** [comment]
Errr...  do you want to elaborate on this?

**Comment by AcarBurak** [comment]
:)
Sorry, absent-mindedness! I've been using `--text-info` together with some `echo` or `printf` commands and in that way I use qarma as a very fast note taker and forgeting all about my use of those `echo` etc. commands, I took qarma to be a genuine text editor, only lacking the auto-save feature!

I feel I'm not still very clear, am I?

Because of a previous issue you've kindly implemented a feature so that issuing
`qOpen=$(qarma --text-info --editable --auto-scroll --width 500 --height 400 --filename=/home/burak/Documents/Not/todo.md) && printf "\n------------\n$qOpen" > /home/burak/Documents/Not/todo.md`
and then Ctrl+enter I can easily edit that file for instance. Now I've thought why not auto-save it instead of the trouble of hitting Ctrl+enter!
