### ISSUE TITLE
Project orientation

### ISSUE THREAD

**Issue by redtide** [luebking/qarma#35]
The last commit was 3 years ago, is this project abandoned? If yes I would be interested to submit some changes but I'm not sure if to do in an own fork with different name or it could be somehow adopted.

**Comment by luebking** [comment]
At soem point I got pretty disappointed (which is a euphemism) w/ Qt's shift towards QML and the quality of the latter throughout the entire Qt5 era and sadly, but essentially turned my back on the framework because of that and have at best put minimum effort into maintaining stuff that I had written (and don't use myself)

tl;dr - idk.
Depends on whether Qt6 is going to be the same garbage geared towards the web-designer approach of "poking around until it the state machine does somehow what I want. At least on my system…"

**Comment by redtide** [comment]
I don't know/care about QML, I don't use it. Qt6 is out already BTW, I don't think they abandoned the v5 way. All I need to know is if I should maintain a fork diverged from this (and so rename it since it's going to not to be the same) or if you can share it in some way, either giving access or transfer it to be continued.

**Comment by luebking** [comment]
As you may or not have noticed, I've picked up development again.

Looking at your fork, the file filtering bug and "--initial" support should be covered
I don't see the need for an external build system (it's a *very* small project) and while the code could be cleaned up (I originally wrote that in one angry night in response to some BS from the gtk bugtracker)
I do not intend to draw git fences w/ refactoring (instead clean up or transition away from legacy Qt/g++ requirements will happen on the fly or if there're actual build issues)

If you want to make a case for other commits/features, I'm listening.

Also sorry for allowing myself to subject you and other actual users to my disappointment w/ Qt's degrading QA.

**Comment by redtide** [comment]
> As you may or not have noticed, I've picked up development again.

No, I didn't, thank you for the notify and welcome back :-).
I was interested on your project mainly to have a valid alternative to Zenity for Qt because it's a dependency of a project I was following until some weeks ago, to provide a file dialog, so only for that feature, I don't use other dialogs, or I haven't tried yet using it with other 2 applications I have installed that require Zenity.

> I don't see the need for an external build system

I use mainly QtCreator as IDE for Qt, which currently supports CMake as it seems will be the new default build system and I converted all my projects to use it instead the old QMake system. Other than that I have other non Qt projects using CMake and I'm fine with QtCreator as IDE for them as well, so one system for all.

> I do not intend to draw git fences w/ refactoring (instead clean up or transition away from legacy Qt/g++ requirements will happen on the fly or if there're actual build issues)

IDK what you mean with that.

> If you want to make a case for other commits/features, I'm listening.

I almost forgot what I did and I need to cross check my changes with yours, I'll do it in a later time and let you know.

**Comment by luebking** [comment]
> IDK what you mean with that.
There seem to be a couple of patches that only sanitize the code (embrace single lines, alter inclusions, move the files, …) which is all nice, but whenever you do any kind of refactoring (and typically touch wider code ranges) you introduce a patch that catches git blame and also makes it hard(er) to revert patches.

**Comment by redtide** [comment]
Oh, maybe you mean about moved files in a `src` directory and added clang-format. I got you didn't have interest to maintain the project anymore so I did major changes following my usual structure and syntax.

**Comment by redtide** [comment]
Hello, finally I had some time to give a look on my changes.
> Looking at your fork, the file filtering bug and "--initial" support should be covered

the --initial option was from PR #29 I merged on my side, if you changed your mind about it you could merge the original if still applies? Otherwise I could send a single PR with it and my file filters changes.

I'm not sure the original file filtering was a bug or just the original way to filter files in Zenity, or maybe I'm just confusing with an unrelated issue which was on KDialog, which was a mess with it, I recall in some project I had to revert with its old way for compatibility.

> If you want to make a case for other commits/features, I'm listening.

looking at my changes, apart irrelevant CMake stuff and refactoring I see 4 other changes that could be applied: my editorconfig and gitignore dotfiles, the `NULL` <-> `nullptr` replacement, the QStrings by ref and the `csignal`: these 3 ones comes from PR #28.

**Comment by luebking** [comment]
I'd like to see the pending file filter changes (on top of the current master)
___
To add the --initial switch, I'd need to hear why the present implementation isn't sufficient for you. Since zenity development seems to have stopped, I'm not *that* concerned about future collisions, but if I can get the feature w/o adding a "proprietary" switch, I'll rather have the free beer.
___
Code modernization will only ever happen gradually. I don't like git fences and don't see the benefit to outweigh them here.

**Comment by redtide** [comment]
> I'd like to see the pending file filter changes (on top of the current master)

IDK what to do with this, you already made your own version, which it looks to work differently.

> To add the --initial switch, I'd need to hear why the present implementation isn't sufficient for you.

I repeat, I just merged an unmerged PR you closed in the past, I don't even recall what that `--initial` was for, and I see no current implementation. This is not important to me, was you asking for this [here](https://github.com/luebking/qarma/issues/35#issuecomment-894674139).

> Code modernization will only ever happen gradually. I don't like git fences and don't see the benefit to outweigh them here.

I could split it in 3 PR if needed, but I really don't see any problem for just 4 references (which is more a bug fix then modernization), 14 `nullptr`s and a single header replacement done in 3 separated commits.
