### ISSUE TITLE
`qarma` is not a drop-in replacement for `zenity`; e.g. the option `--mid-search` is not honoured.

### ISSUE THREAD

**Issue by felixbecker2** [luebking/qarma#36]
`qarma` is not a drop-in replacement for `zenity`. For example, `zenity`'s option `--mid-search` is not honoured by `qarma`:

For example, the command

```
zenity --list --mid-search --window-icon question --title "Automirror" --text="Please select the primary output. All other outputs will be scaled to match." --column Output --column "Width [mm]" --column "Height [mm]" --column "Width [px]" --column "Height [px]"
```
*(Taken from [&rarr; this script](https://github.com/schlomo/automirror/blob/master/automirror.sh))*

displays correctly in `zenity`, while with `qarma` it produces a spurious `--mid-search` in the output (`qarma` seems not to handle this correctly). [&rarr; Here](/schlomo/automirror/issues/5) is a screenshot of what happens with `qarma`.

Thanks for maintaining!

**Comment by maz-1** [comment]
Just to let you know, i forked this repo and added --mid-search: https://github.com/maz-1/qarma
It's just a placeholder and does not actually do anything, but at least no messy list anymore.
I can't figure out what --mid-search actually does, can you help?

**Comment by felixbecker2** [comment]
Hey,

> i forked this repo and added --mid-search: https://github.com/maz-1/qarma It's just a placeholder and does not actually do anything, but at least no messy list anymore.

Thanks for your work!

Maybe you can send the patch to the maintainers of the official `qarma` sources?

> I can't figure out what --mid-search actually does, can you help?

I also don't know. I found it also in just a script from somewhere else, which I used. My manpage of `zenity` does not document it.

-- 
Most bacteria have the decency to be microscopic. Epulopiscium
fishelsoni is not among them. The newly identified one-celled
macro-microorganism is a full .5 mm long, large enough to be seen
with the naked eye. Described in the current Nature, "It is a
million times as massive as a typical bacterium."
                      - Time, page 25, March 29, 1993

**Comment by maz-1** [comment]
I would like to, but the option is not actually implemented and seems the repo is not actively mantained as several pull requests are not responded.

**Comment by luebking** [comment]
```
%  zenity --help-list
…
  --mid-search         Change list default search function searching for text in the middle, not on the beginning
```

When you start typing, zenity selects a matching list element - mid-search matches any .*pattern.*, otherwise it's "^pattern.*"
