### ISSUE TITLE
Having issue with pipelight

### ISSUE THREAD

**Issue by maz-1** [luebking/qarma#4]
pipelight use zenity to show a progress window when installing plugins
however qarma does not work right with it. The progress window keep forever and plugin installer won't finish
the command from ps -ef:
zenity --progress --title=Please wait, installing ... --text=Running wine-unity3d-installer --pulsate --width=400 --auto-close --no-cancel

**Comment by luebking** [comment]
Actually, that's exactly what the commandline says.
--pulsate is an infinite progress (the indicator just slides back and forth) and --auto-close doesn't seem to make much sense in this regard.

If you run that command with zenity, you'll simply get an infinitely running zenity dialog, so the problem will be how pipelight (or whatever ulltimately invokes it) attempts to close the dialog.

I guess you're symlinking qarma to zenity? What if you copy it there instead?

**Comment by maz-1** [comment]
no , copy qarma to zenity won't work
by the way ,this is what I found in the installer script


 progressbar()
	{
		WINDOWID="" zenity --progress --title="$1" --text="$2" --pulsate --width=400 --auto-close --no-cancel ||
		WINDOWID="" zenity --progress --title="$1" --text="$2" --pulsate --width=400 --auto-close
	}

DISPLAY="" "$WINE" wineboot.exe 2>&1 | progressbar "Please wait..." "Creating wine prefix"


So when the pipe is broken , the dialog box is expected to exit.

**Comment by maz-1** [comment]
I tried
sleep 5 | qarma --progress --pulsate --auto-close --no-cancel
and
sleep 5 | zenity --progress --pulsate --auto-close --no-cancel

zenity exits, qarma won't.
