### ISSUE TITLE
Qarma::notify() hides overloaded virtual function QApplication::notify(QObject*, *QEvent*)

### ISSUE THREAD

**Issue by redtide** [luebking/qarma#45]

**Comment by luebking** [comment]
Clang or do you explicitly issue -Woverloaded-virtual ?
The warning is a false postive (and probably the reason why gcc has - had? - it disabled by default)

I'll silence it but nb. that there's nothing wrong w/ the code - just a hyperactive compiler.

**Comment by redtide** [comment]
Just noticed with line annotations enabled in QtCreator, it's OK then.
