### ISSUE TITLE
doesn't detect KP_Enter key

### ISSUE THREAD

**Issue by AcarBurak** [luebking/qarma#5]
In "--text-info --editable" windows/dialogues the standart Return key produces a carriage return naturally, so to be able to easily click OK (without recourse to mouse) I've thought I need Keypad Enter key (KP_Enter) which my Apple mini keyboard lacks. To workaround I've edited the /usr/share/X11/xkb/symbols/inet and replaced the line

    key <I238>   {      [ XF86KbdBrightnessUp   ]       }; // KEY_KBDILLUMUP

with

    key <I238>   {      [ KP_Enter   ]       }; // KEY_KBDILLUMUP

Now the intended key, according to `xev` output as well, works as KP_Enter. Yet it hasn't made a difference with Qarma, it still works like a regular Return key producing a carriage return.

All this in a pure Qt5 Arch Fluxbox system if that matters.

By the way, thanks very much for providing this very fine utility without the GTK cruft.

**Comment by luebking** [comment]
QTextEdit doesn't make a difference between Qt::Key_Return and Qt::Key_Enter - it accepts both events (so the key doesn't make it to the dialog from there)

I could probably catch & override that, but the textedit in qarma would then work fundamentally different from any other textedit (and trap users into accidentally accept the dialog while typing, eg. using the numpad to enter numbers)

Did you try this with actual zenity? (I've no idea how gtk acts itr.)

**Comment by AcarBurak** [comment]
All right, not a big deal really. Thank you for the explanation.

No, I haven't try zenity, I'm GTK-free!

**Comment by luebking** [comment]
Ctrl+Enter actually should work ootb.
Ctrl+Return does not, but I added a shortcut to align them.

**Comment by AcarBurak** [comment]
Thank you sir, works beautifully.
