### ISSUE TITLE
Selectable Labels in QMessageBox (Feature Request)

### ISSUE THREAD

**Issue by tsujan** [luebking/qarma#8]
Yad has a `--selectable-labels` option, which is handy in some scripts. Qarma could also have it easily by introducing a boolean `selectable` under `Qarma::showMessage()`:
````
bool selectable = false;
...
else if (args.at(i) == "--selectable-labels")
    selectable = true;
````
and adding:
````
if (selectable)
    l->setTextInteractionFlags(Qt::TextSelectableByMouse);
````

Sorry, I should have made a PR but didn't have time.

**Comment by luebking** [comment]
https://github.com/luebking/qarma/commit/6bcbe6b6f34d3dc2ab1efcf9ff0180083c23fa82

Sorry for the delay. Thing's that I'm decreasingly using Qt at all :-(

**Comment by tsujan** [comment]
> Sorry for the delay.

It's OK! I'd changed the code for my personal use.

> Thing's that I'm decreasingly using Qt at all

Just out of curiosity, may I ask why -- have you found a better toolkit?

**Comment by luebking** [comment]
The drift towards QtQuick - I don't think the desktop is a relevant target any longer and frankly consider QtQuick of inferior quality (while Qt5 QWidget code turns bitrot)

Better toolkit? ncurses? ;-)
No, not really "better", but preparing for a worse future of Qt.

**Comment by tsujan** [comment]
Interesting!
As for QtQuick,I agree with you. I don't understand why most people say good things about it. IMO, it's very "lame", at least, in its current state.
