### ISSUE TITLE
Tag release?

### ISSUE THREAD

**Issue by zx2c4** [luebking/qarma#9]
Can you tag a release so I can package this for Gentoo?

**Comment by luebking** [comment]
Added https://github.com/luebking/qarma/releases/tag/t1
Emerge doesn't git?

**Comment by zx2c4** [comment]
It will, but it will be masked. Stable operating systems need real releases -- debian, ubuntu, fedora, opensuse, gentoo, ... the whole family. Please take this seriously.

Thanks for the tag. I'm packaging it now.

**Comment by zx2c4** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=42750c012dfe567dbb17557346d3ab02a2d5a128
